/* Generated by generate-megarom.py; ASCII16-X banked data. */
#define BANK_BACKGROUND 1
#define BANK_ORB 3
#define BANK_PANEL 4
#define BANK_CORE 5
#define BANK_SHARDS 7
#define BANK_ROTATION 9
#define BANK_MESH 10
#define BANK_FLOOR 42
#define BANK_WATER 46
#define BANK_IDENTITY 54
#define BANK_LABELS 55
#define BANK_SEABED 56
#define MEGAROM_BYTES 1048576UL
